#!/usr/bin/env sh
printf "20 text/gemini\r\n"
printf "yatb (yet another tech gemlog)\r\n\r\n"
user=$(stat -c '%U' $0)
find /var/gemini/nytpu.com/gemlog/ -type f -name '*.md' -maxdepth 1 -print0 | xargs -0 ls -t | sort | while read file; do
post=$(basename $file)
printf "=> /gemlog/$post $post\r\n" 
done

printf "\r\n\r\n"
printf "this gemlog/phlog/blog is mirrored on gopher at:\r\n"
printf "=> gopher://nytpu.com/phlog/\r\n\r\n"
#printf "it's also mirrored on the web at:\r\n"
#printf "=> https://tilde.team/~$user/blog/\r\n\r\n"
#printf "=> gemini://tilde.team/~$user/ or go back to my main gemini page\r\n"
